/// Flutter icons AnalogClock
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AnalogClock
///      fonts:
///       - asset: fonts/AnalogClock.ttf
///
///
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
///
import 'package:flutter/widgets.dart';

class AnalogClock {
  AnalogClock._();

  static const _kFontFam = 'AnalogClock';

  static const IconData snow_heavy_inv =
      const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData clouds_inv =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData fog = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData rain_inv =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData sun_inv = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData clouds_flash_inv =
      const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData clouds_flash_alt =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData celcius = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData fahrenheit =
      const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData temperature =
      const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData rain = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData snow_heavy =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData cloud_flash =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData cloud = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData cloud_inv =
      const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData cloud_flash_inv =
      const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData clouds = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData clouds_flash =
      const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData mist = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData wind = const IconData(0xe815, fontFamily: _kFontFam);
}
